title: ""
description: "Glossario terminologico bilingue (Italiano-Francese) dedicato all'arte e all'architettura di Palazzo Balbi Senarega."
baseurl: "/glossariobalbisenarega"
url: "https://g-mantegazza.github.io"

# Informazioni istituzionali e autore
author:
  name: "Giovanni Mantegazza"
  institution: "Università degli Studi di Genova"
  center: "Centro di Ricerca in Terminologia Multilingue (CeRTeM)"

# Motore di Markdown
markdown: kramdown
permalink: /:basename/
